[env:ieum]
custom_meshtastic_architecture = nrf52840
custom_meshtastic_display_name = Ieum
custom_meshtastic_tags = IEUM

extends = nrf52840_base
board = wiscore_rak4631
board_level = extra
board_check = true
build_type = release
build_flags =
  ${nrf52840_base.build_flags}
  -I variants/nrf52840/ieum
  -D IEUM
  -D PRIVATE_HW
  -D CONFIG_NFCT_PINS_AS_GPIOS=1
  -D HAS_GPS=0
  -D HAS_SCREEN=0
  -D MESHTASTIC_USE_EINK_UI=0
  -D RADIOLIB_EXCLUDE_SX128X=1
  -D RADIOLIB_EXCLUDE_SX127X=1
  -D RADIOLIB_EXCLUDE_LR11X0=1
build_src_filter =
  ${nrf52_base.build_src_filter}
  +<../variants/nrf52840/ieum>
lib_deps =
  ${nrf52840_base.lib_deps}
